---
- name: Ensure the required NuGet package provider version is installed
  ansible.windows.win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

- name: Install DSC Modules
  win_psmodule:
    name: "{{ dsc_module_loop }}"
    state: present
    accept_license: true
    allow_prerelease: true
  loop:
    - ActiveDirectoryDsc
    - xDnsServer
  loop_control:
    loop_var: dsc_module_loop