---
- hosts: all
  vars_prompt:
    - name: ansible_pass
      prompt: "Please enter account password"
  vars:
    ansible_password: "{{ ansible_pass }}"
  vars_files:
    - "group_vars/windows.yml"
  roles:
    - role: add_dns_record
      tags: [ add_dns_record ]